- name: Install Weeveley3 requirements
  ansible.builtin.pip:
    name:
      - prettytable
      - Mako
      - PyYAML
      - python-dateutil
      - PySocks
      - pyOpenSSL
      - setuptools
      - telnetlib3
    virtualenv: /opt/virtual_environments/weevely
    virtualenv_site_packages: yes
    virtualenv_command: "python3 -m venv"
- name: Install the Python tool in the virtual environment
  ansible.builtin.git:
    repo: 'https://github.com/epinna/weevely3.git'
    dest: /home/kali/tools/weevely
    force: yes

- name: Replace string to execute
  ansible.builtin.lineinfile:
    path: /home/kali/tools/weevely/weevely.py
    search_string: '#!/usr/bin/env python'
    line: '#!/opt/virtual_environments/weevely/bin/python3'

- name: Replace string to execute
  ansible.builtin.lineinfile:
    path: /home/kali/tools/weevely/modules/backdoor/tcp.py
    search_string: 'import telnetlib'
    line: 'import telnetlib3'
