- name: Create ssf directory
  ansible.builtin.file:
    path: /home/kali/tools/ligolo-ng
    state: directory
    owner: kali

- name: Download ligolo binaries
  ansible.builtin.unarchive:
    src: "{{ item }}"
    dest: /home/kali/tools/ligolo-ng
    owner: kali
    remote_src: yes
  loop:
  - https://github.com/nicocha30/ligolo-ng/releases/download/v0.8/ligolo-ng_agent_0.8_linux_amd64.tar.gz
  - https://github.com/nicocha30/ligolo-ng/releases/download/v0.8/ligolo-ng_agent_0.8_windows_amd64.zip
  - https://github.com/nicocha30/ligolo-ng/releases/download/v0.8/ligolo-ng_proxy_0.8_linux_amd64.tar.gz
