- name: Install Pivotnacci requirements
  ansible.builtin.pip:
    name:
      - pivotnacci
    virtualenv: /opt/virtual_environments/pivotnacci
    virtualenv_site_packages: yes
    virtualenv_command: "python3 -m venv"
- name: Install the Python tool in the virtual environment
  ansible.builtin.git:
    repo: 'https://github.com/blackarrowsec/pivotnacci.git'
    dest: /home/kali/tools/pivotnacci
    force: yes

- name: Replace string to execute
  ansible.builtin.lineinfile:
    path: /home/kali/tools/pivotnacci/pivotnacci
    search_string: '#!/usr/bin/env python'
    line: '#!/opt/virtual_environments/pivotnacci/bin/python3'

