- name: Create gost directory
  ansible.builtin.file:
    path: /home/kali/tools/gost
    state: directory
    owner: kali

- name: Download gost
  ansible.builtin.unarchive:
    src: https://github.com/ginuerzh/gost/releases/download/v2.12.0/gost_2.12.0_linux_amd64.tar.gz
    dest: /home/kali/tools/gost
    owner: kali
    remote_src: true
